### ISSUE TITLE
Fill new folders.

### ISSUE THREAD

**Issue by ghost** [AgoutiGames/TerraAustralis#10]
Place the files in the appropriate new folders where they belong. 
Especially the actors are very important!

**Comment by Moonlighthiker** [comment]
I've added a "sounds" and a "music" folder. 
I didn't make the other changes anymore, I'm too tired. Must sleep.

**Comment by VectorWolf** [comment]
I''ll best combine this with the "janitor work" i promised to do since a long time :-D
